# Sección 2 - Arrays

Durante esta sección vamos a trabajar con el tipo de datos "array", aprendiendo como podemos generarlos, recorrerlos, consultarlos, etc. 

## Lección 1 - Creación de arrays

In [3]:
import numpy as np

Comenzamos creando distintos tipos de arrays simples

Un ***ndarray*** es un conjunto multidimensional (generalmente de tamaño fijo) de elementos del mismo tipo y tamaño. El número de dimensiones y elementos en una matriz se define por su forma, que es una tupla de N números enteros no negativos que especifican los tamaños de cada dimensión. El tipo de elementos de la matriz se especifica mediante un objeto de tipo de datos independiente (dtype), uno de los cuales está asociado con cada ndarray.

El constructor a bajo nivel de **ndarray** es *np.ndarray*, pero no se recomienda su uso. Para la creación de arrays, se recomienda usar los métodos:
- [array](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array): Construye un nuevo array
- [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros): Construye un array de zeros
- [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones): Construye un array vacío

También es intesante el método *dtype*

<img src=https://numpy.org/doc/stable/_images/threefundamental.png>

Vamos a usar dichos métodos para crear nuevos arrays.

#### array

In [18]:
array1 = np.array([1,2,3,4,5,6], dtype = 'int')
print(type(array1))
array1


<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [27]:
array2 = np.array([[1,2,3],[4,5,6]], dtype = 'int', ndmin=2 )
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
array3 = np.array([1,2,3], dtype = 'complex')
array3

array([1.+0.j, 2.+0.j, 3.+0.j])

#### zeros

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### ones

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### range

In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Lección 2 - Tipos de datos

In [2]:
import numpy as np

Python define solo un tipo por cadaclase de datos en particular (solo hay un tipo de entero, un tipo de float, etc.). Esto puede tener sentido en aplicaciones que no necesitan preocuparse por las distintas formas en en que se pueden representar los datos en un ordenador. Sin embargo, cuando trabajamos con el análisis de datos, a menudo necesitamos más control. 

En NumPy, hay 24 nuevos tipos fundamentales de Python para describir diferentes tipos de escalares. Estos descriptores de tipo se basan principalmente en los tipos disponibles en el lenguaje C en el que está escrito CPython, con varios tipos adicionales compatibles con los tipos de Python.

Los diferentes tipos de datos están organizados de manera jerárquica como representa la siguiente figura:

<img src=https://numpy.org/doc/stable/_images/dtype-hierarchy.png>

In [25]:
a = np.array([1,2,3,4], dtype=np.int_)
a

array([1, 2, 3, 4])

In [34]:
bool_array = np.array([[1,0,0,1], [0,1,1,0]], dtype = np.bool)
bool_array

array([[ True, False, False,  True],
       [False,  True,  True, False]])

In [62]:
char_array = np.array(['a','b','c'], dtype = np.chararray)
char_array

array(['a', 'b', 'c'], dtype=object)

Además, cada uno de los tipos de la jerarquía que vemos arriba, poseen tipos de datos con distinto tamaño. Esto significa, capaces de almacenar un número distinto de bits. Por ejemplo: 

Para los ***int*** tenemos:
- int8 &rarr; Máximo 8 bits
- int16 &rarr; Máximo 16 bits
- int32 &rarr; Máximo 32 bits
- int64 &rarr; Máximo 64 bits

Para los ***float*** tenemos:
- float16 &rarr; Máximo 16 bits
- float32 &rarr; Máximo 32 bits
- float64 &rarr; Máximo 64 bits

Podéis encontrar todos los tipos de datos en el siguiente [enlace](https://numpy.org/doc/stable/reference/arrays.scalars.html#built-in-scalar-types)

In [28]:
from sys import getsizeof

a = np.array([1,2,3,4], dtype = np.int8)
b = np.array([1,2,3,4], dtype = np.int64)

print("A", getsizeof(a))
print("B", getsizeof(b))

A 100
B 128


Podemos consultar el tipo de datos de un array con el método *dtype*

In [35]:
print(a.dtype)
print(b.dtype)

print(bool_array.dtype)

int8
int64
bool


In [51]:
dt = np.dtype('int32')
print(dt.type)
dt.type is np.int32

<class 'numpy.int32'>


True

Además, podemos crear tipos de datos con una combinación de 'carácter' + 'nº de bytes'. Los carácter que podemos usar son:

- '?' : boolean
- 'b' : (signed) byte
- 'B' : unsigned byte
- 'i' : (signed) integer
- 'u' : unsigned integer
- 'f' : floating-point
- 'c' : complex-floating point
- 'm' : timedelta
- 'M' : datetime
- 'O' : (Python) objects
- 'S', 'a' : zero-terminated bytes (not recommended)
- 'U' : Unicode string
- 'V' : raw data (void)

In [53]:
dt = np.dtype('f8')
a = np.array([1,2,3,4], dtype = dt)
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


In [54]:
dt = np.dtype('int32')
dt.kind

'i'

Un tipo de dato muy importante en Numpy es el NaN, o valor nulo.

In [133]:
nan = np.nan
np.isnan(nan)

True

In [134]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

#### El tipo matrix

Los objetos de matriz heredan del ndarray y, por lo tanto, tienen los mismos atributos y métodos que ndarrays. Sin embargo, las matrices solo pueden tener dimensión 2. 

In [55]:
m = np.matrix('1 2 3 ; 4 5 6')
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [58]:
m = np.mat([[1,2,3], [3,4,5]], dtype = np.float16)
m

matrix([[1., 2., 3.],
        [3., 4., 5.]], dtype=float16)

In [61]:
a = np.array([[1,2,3], [3,4,5]], dtype = np.float16)
print(type(a))
m = np.asmatrix(a)
print(type(m))
m

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


matrix([[1., 2., 3.],
        [3., 4., 5.]], dtype=float16)