# Ejercicios lecciones 1-4

In [1]:
import numpy as np

## Ejercicio 1

Genera un array que contenga 25 elementos entre 0 y 99 siguiendo una distribución lineal. Luego, transforma ese array en una matriz de 5 x 5. ¿Cuál es la diagonal de la matriz? ¿Y la diagonal justo superior?

In [4]:
a = np.linspace(start=0, stop=100, num = 25, endpoint=False)
a

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48.,
       52., 56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.])

In [5]:
m = a.reshape(5,5)
m

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.]])

In [7]:
np.diag(m)

array([ 0., 24., 48., 72., 96.])

In [8]:
np.diag(m, k=1)

array([ 4., 28., 52., 76.])

## Ejercicio 2

Crea un de 5 x 4 con el valor repetido 10. Une esa matriz a la matriz del ejercicio anterior para conseguir dos nuevas matrices, una de  5 x 9, y otra de 9 x 5.

$m = \begin{pmatrix}
0 & 4 & 8 & 12 & 16 \\
20 & 24 & 28 & 32 & 36 \\
40 & 44 & 48 & 52 & 56 \\
60 & 64 & 68 & 72 & 76 \\
80 & 84 & 88 & 92 & 96
\end{pmatrix}$
$m2 = \begin{pmatrix}
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 & 5 & 5
\end{pmatrix}$

In [24]:
m2 = np.repeat(5, 20).reshape(4,5)
m2

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [25]:
np.concatenate((m, m2), axis = 0)

array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.],
       [80., 84., 88., 92., 96.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.]])

In [26]:
np.concatenate((m, m2.T), axis = 1)

array([[ 0.,  4.,  8., 12., 16.,  5.,  5.,  5.,  5.],
       [20., 24., 28., 32., 36.,  5.,  5.,  5.,  5.],
       [40., 44., 48., 52., 56.,  5.,  5.,  5.,  5.],
       [60., 64., 68., 72., 76.,  5.,  5.,  5.,  5.],
       [80., 84., 88., 92., 96.,  5.,  5.,  5.,  5.]])

### Ejercicio 3

Teniendo el array inicial que podéis ver justo abajo, debéis realizar las operaciones necesarias para obtener el array: 
    
array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

¿Qué elementos del array comienzan por 'E'?

In [59]:
a = np.array(['     este es un curso de openwebinars    '])
a

array(['     este es un curso de openwebinars    '], dtype='<U41')

In [60]:
a1 = np.char.strip(a)
a1

array(['este es un curso de openwebinars'], dtype='<U41')

In [61]:
a2 = np.char.split(a1, ' ')
a2 = np.array(a2[0])
a2

array(['este', 'es', 'un', 'curso', 'de', 'openwebinars'], dtype='<U12')

In [62]:
a3 = np.char.capitalize(a2)
a3

array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

In [63]:
e = np.char.startswith(a3, 'E')
e

array([ True,  True, False, False, False, False])

In [64]:
a3[e]

array(['Este', 'Es'], dtype='<U12')

### Ejercicio 4

Considerando las matrices A y B. 

$A = \begin{pmatrix}
3 & 1 & 2 \\
4 & 1 & 3 \\
2 & 0 & 1
\end{pmatrix}$
$B = \begin{pmatrix}
2 & 0 & 3 \\
1 & 1 & 1 \\
0 & 2 & 4
\end{pmatrix}$

- Realiza la multiplicación matricial de AxB y BxA. ¿Son iguales?
- Realiza la multiplicación de la matriz A x 2
- ¿Cúanto es la multiplicación escalar de AxB? ¿y de BxA?

In [65]:
a = np.array([[3,1,2], [4,1,3], [2,0,1]])
b = np.array([[2,0,3], [1,1,1], [0,2,4]])

print(a)
print(b)

[[3 1 2]
 [4 1 3]
 [2 0 1]]
[[2 0 3]
 [1 1 1]
 [0 2 4]]


In [67]:
# Realiza la multiplicación matricial de AxB y BxA. ¿Son iguales?

axb = np.dot(a,b)
axb

array([[ 7,  5, 18],
       [ 9,  7, 25],
       [ 4,  2, 10]])

In [68]:
bxa = np.dot(b,a)
bxa

array([[12,  2,  7],
       [ 9,  2,  6],
       [16,  2, 10]])

¡No son iguales! El producto matricial es distinto

In [69]:
# Realiza la multiplicación de la matriz A x 2
a * 2

array([[6, 2, 4],
       [8, 2, 6],
       [4, 0, 2]])

In [70]:
# ¿Cúanto es la multiplicación escalar de AxB?
np.vdot(a,b)

24

In [71]:
np.vdot(b,a)

24

¡En este caso si son iguales! Puesto que estamos multiplicando escalarmente.

## Ejercicio 5

Usando la matriz A del ejercicio anterior, calcula:

- A^3
- El determinante de A
- Resuelve la ecuación Ax = y, siendo ***y*** el array [3,2,5]

In [86]:
a

array([[3, 1, 2],
       [4, 1, 3],
       [2, 0, 1]])

In [87]:
b

array([[2, 0, 3],
       [1, 1, 1],
       [0, 2, 4]])

In [88]:
# A^3
a3 = np.linalg.matrix_power(a, 3)
a3

array([[ 89,  21,  57],
       [114,  27,  73],
       [ 42,  10,  27]])

Comprobamos realizando la multiplicación matricial

In [89]:
_ = np.dot(a, a)
np.dot(_, a)

array([[ 89,  21,  57],
       [114,  27,  73],
       [ 42,  10,  27]])

In [90]:
# El determinante de A
np.linalg.det(a)

1.0

In [91]:
# Resuelve la ecuación Ax = y, siendo y el array [3,2,5]
y = np.array([3,2,5])

In [92]:
np.linalg.solve(a, y)

array([ 6., -1., -7.])