# Sección 2 - Arrays

Durante esta sección vamos a trabajar con el tipo de datos "array", aprendiendo como podemos generarlos, recorrerlos, consultarlos, etc. 

## Lección 1 - Creación de arrays

In [3]:
import numpy as np

Comenzamos creando distintos tipos de arrays simples

Un ***ndarray*** es un conjunto multidimensional (generalmente de tamaño fijo) de elementos del mismo tipo y tamaño. El número de dimensiones y elementos en una matriz se define por su forma, que es una tupla de N números enteros no negativos que especifican los tamaños de cada dimensión. El tipo de elementos de la matriz se especifica mediante un objeto de tipo de datos independiente (dtype), uno de los cuales está asociado con cada ndarray.

El constructor a bajo nivel de **ndarray** es *np.ndarray*, pero no se recomienda su uso. Para la creación de arrays, se recomienda usar los métodos:
- [array](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array): Construye un nuevo array
- [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros): Construye un array de zeros
- [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones): Construye un array vacío

También es intesante el método *dtype*

<img src=https://numpy.org/doc/stable/_images/threefundamental.png>

Vamos a usar dichos métodos para crear nuevos arrays.

#### array

In [18]:
array1 = np.array([1,2,3,4,5,6], dtype = 'int')
print(type(array1))
array1


<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [27]:
array2 = np.array([[1,2,3],[4,5,6]], dtype = 'int', ndmin=2 )
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
array3 = np.array([1,2,3], dtype = 'complex')
array3

array([1.+0.j, 2.+0.j, 3.+0.j])

#### zeros

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### ones

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### range

In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])