In [2]:
import numpy as np

### Ejercicio 1

Crea 3 nuevos arrays. 
- Array de tipo entero, que contenga solo los números impares del 1 al 100. 
- Array de tipo cadena con tu nombre y apellidos
- Array de tipo fechas, que contenga todos los días desde el 01Enero2020 al 04Febrero2020

In [5]:
array_impares = np.arange(1, 100, 2)
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [6]:
_ = np.arange(1,100)
array_impares = _[_ % 2 != 0]
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [7]:
datos = np.array(['Abraham', 'Requena', 'Mesa'])
datos

array(['Abraham', 'Requena', 'Mesa'], dtype='<U7')

In [10]:
array_fechas = np.arange('2020-01-01', '2020-02-04', dtype='datetime64[D]')
array_fechas

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
       '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
       '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01',
       '2020-02-02', '2020-02-03'], dtype='datetime64[D]')

### Ejercicio 2

Recupera los últimos 10 elementos del array de impares

In [26]:
array_impares[:len(array_impares)-11:-1]

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81])

### Ejercicio 3

Recorre el array de fechas, y genera un nuevo numpy array que contenga unicamente los días laborales

In [30]:
laborables = []
for fecha in array_fechas:
    if np.is_busday(fecha):
        laborables.append(fecha)
laborables_array = np.array(laborables, dtype = 'datetime64')

laborables_array

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-06',
       '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-20', '2020-01-21', '2020-01-22',
       '2020-01-23', '2020-01-24', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-03'],
      dtype='datetime64[D]')

Otra forma de hacerlo sería:

In [31]:
array_fechas[np.is_busday(array_fechas)]

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-06',
       '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-20', '2020-01-21', '2020-01-22',
       '2020-01-23', '2020-01-24', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-03'],
      dtype='datetime64[D]')

### Ejercicio 4

Genera la siguiente matriz. 

$A = \begin{pmatrix}
10 & 1 & 8 & 4 \\
3 & 7 & 2 & 1 \\
0 & 2 & 20 & 12 \\
\end{pmatrix}$

¿De qué tipo es?
Luego, implementa una máscara a todos los números de la matriz mayores o iguales a 10

In [33]:
A = np.matrix('10 1 8 4 ; 3 7 2 1 ; 0 2 20 12')
A

matrix([[10,  1,  8,  4],
        [ 3,  7,  2,  1],
        [ 0,  2, 20, 12]])

In [34]:
A.dtype

dtype('int64')

In [38]:
import numpy.ma as ma

A_masked = ma.masked_greater_equal(A, 10)
A_masked

masked_matrix(
  data=[[--, 1, 8, 4],
        [3, 7, 2, 1],
        [0, 2, --, --]],
  mask=[[ True, False, False, False],
        [False, False, False, False],
        [False, False,  True,  True]],
  fill_value=999999)

### Ejercicio 5

Crea dos fechas, la primera de ellas será tu fecha de nacimiento, y la segunda, la de un familiar o amigo tuyo. 

- ¿Qué diferencia en horas hay entre las dos fechas?
- ¿Cual sería tu fecha de nacimiento si hubieras nacido 236 horas antes?

In [48]:
fech_naci = np.datetime64('1993-05-03')
fech_naci_hermano = np.datetime64('1985-12-11')

diff = fech_naci - fech_naci_hermano
np.timedelta64(diff, 'h')

print(f"Mi hermano es {str(np.timedelta64(diff, 'h'))} horas mayor que yo")

h = np.timedelta64(236, 'h')
nueva_fechnaci = fech_naci - h
print(f"Mi fecha de nacimiento sería {str(nueva_fechnaci)}")

Mi hermano es 64800 hours horas mayor que yo
Mi fecha de nacimiento sería 1993-04-23T04
