# Sección 3 - Operaciones con Numpy

Durante esta sección vamos a conocer las diferentes operaciones que tenemos disponibles en Numpy. Una vez conocido en profundidad el tipo array, ahora vamos a conocer el amplio abanico de operaciones que tenemos disponibles en la librería. Hablaremos de la manipulación y procesamiento de datos, así como de funciones lógicas, matemáticas o estadísticas.

In [1]:
import numpy as np

## Leccion 1 - Rutinas de creación de arrays

Hasta ahora hemos visto como crear arrays haciendo uso del contructor **ndarray**, pero numpy nos proporciona una serie de rutinas para facilitarnos dicha creación. Veamos algunas de ellas.

### Unos y ceros

In [3]:
# Eye - Devuelve una matriz 2-D con unos en la diagonal y ceros en el resto

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Posee un parámetro *k* para poder desplazar la diagonal principal.

In [8]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [9]:
# identity - Devuelve un array identidad
np.identity(4, dtype = 'int8')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [13]:
# ones - Devuelve un array de unos. Podemos definir su dimension
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# zeros - Devuelve un array de zeros. Podemos definir su dimension
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# full - Devuelve una nueva matriz de forma y tipo dados, rellena con fill_value.
np.full(shape=(4,4), fill_value=99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [16]:
np.full(shape=(4,4), fill_value=[10,20,30,40])

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

### Creación desde datos existentes

In [19]:
# fromstring - Una nueva matriz 1-D inicializada a partir de datos de texto en una cadena.
np.fromstring('1 2 3 4' , sep = ' ')

array([1., 2., 3., 4.])

In [23]:
datos = np.loadtxt('./Leccion 1 - Rutinas de creación de arrays/datos.txt', delimiter=' ', )
datos

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### Rangos numéricos

In [24]:
# arange - Devuelve un array de los valores existentes en un invervalo definido. Podemos 
# configurar el tamaño del paso
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [25]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [31]:
# linspace - Devuelve un número de valores entre un intervalo
np.linspace(start=1, stop=10, num = 5, endpoint=False, retstep=True)

(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)

In [36]:
np.linspace(start=2, stop= 3.5, num = 10)

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        , 3.16666667, 3.33333333, 3.5       ])

In [35]:
# logspace - Igual, pero aplicando una escala logaritmica
np.logspace(start=2, stop= 3.5, num = 10)

array([ 100.        ,  146.77992676,  215.443469  ,  316.22776602,
        464.15888336,  681.29206906, 1000.        , 1467.79926762,
       2154.43469003, 3162.27766017])

- 10 ** 2 = 100
- 10 ** 2.166667 = 146.779
- 10 ** 2.333333 = 215.443

Y así sucesivamente

### Creación de matrices

In [39]:
# diag - Extrae la diagonal de una matriz o array de dos dimensiones

a = np.eye(N = 4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.diag(a)

array([1., 1., 1., 1.])

In [41]:
np.diag(a, k = 1)

array([0., 0., 0.])

In [42]:
# diagflat - Crea una matriz bidimensional con la entrada usada como diagonal.
np.diagflat(v = [1,2,3,4], k = 0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [43]:
np.diagflat(v = [1,2,3,4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [45]:
# tri - Una matriz con unos en la diagonal y debajo de ella, y ceros en cualquier otro lugar.
np.tri(N = 5, M = 5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [46]:
# asmatrix - Crea un tipo matrix a partir de un array

a = np.array([[1,2,3,4], [4,3,2,1]])
np.asmatrix(a)

matrix([[1, 2, 3, 4],
        [4, 3, 2, 1]])

## Leccion 2 - Manipulación de arrays

### Dimensiones del array

In [63]:
# shape - Recuperas la dimension
a = np.array([[1,2,3,4], [4,3,2,1]])
a.shape

(2, 4)

In [64]:
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [65]:
# reshape - Modificar la dimension
a.reshape((4,2))

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [66]:
# ravel - Aplana un array de más de 1D
a.ravel()

array([1, 2, 3, 4, 4, 3, 2, 1])

In [67]:
# T - Transpone filas y columnas
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [68]:
a.T

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

### Tipos de arrays

In [69]:
# asarray - Convierte una lista python en numpy array
np.asarray([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [75]:
# asfarray - Igual, pero devuelve el array de tipo float
np.asfarray([1,2,3,4])

array([1., 2., 3., 4.])

In [77]:
np.asfarray([1,2,3,4], dtype = np.int8)

array([1., 2., 3., 4.])

In [80]:
# asarray_chkfinite - Convierte la entrada en un array, verificando NaN o Infs.

a = [1,2,3,4, np.nan]
np.asarray_chkfinite(a)

ValueError: array must not contain infs or NaNs

In [113]:
# repeat - Genera un array de números iguales
a = np.repeat(a = 99, repeats=10)
a

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [114]:
a.reshape((2,5))

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

### Union de arrays

In [89]:
# concatenate - Une un conjunto de arrays por filas o columnas

a = np.array([[1,2,3,4], [1,2,3,4]])
b = np.array([[4,3,2,1]])

print(a.shape)
print(b.shape)

(2, 4)
(1, 4)


In [90]:
np.concatenate((a,b), axis = 0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])

In [95]:
np.concatenate((a.T, b.T), axis=1)

array([[1, 1, 4],
       [2, 2, 3],
       [3, 3, 2],
       [4, 4, 1]])

In [100]:
# stack - Parecido a join, pero genera un nuevo indice
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

np.stack(arrays=(a,b), axis = 1)

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

In [101]:
np.stack(arrays=(a,b), axis = 0)

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

### Division de arrays

In [105]:
# split - Divide un array en varios 
a = np.arange(0, 20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [106]:
np.split(a, indices_or_sections=4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [109]:
np.split(a, [3, 5, 10, 16])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19])]

### Añadir y eliminar elementos

In [ ]:
# insert - Inserta elementos en una posicion del array

In [115]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [121]:
np.insert(a, obj=4, values=[5,6])

array([1, 2, 3, 4, 5, 6])

In [120]:
np.insert(a, obj=1, values=[5,6])

array([1, 5, 6, 2, 3, 4])

In [124]:
# append - Inserta elementos al final del array
np.append(a, [5,6])

array([1, 2, 3, 4, 5, 6])

In [127]:
# delete - Elimina un elemento del array
np.delete(a, obj = 3)

array([1, 2, 3])

In [128]:
# trim_zeros - Elimina los 0s al inicio y el final del array
a = np.array([0, 0, 0, 0, 1, 2, 3, 4, 0, 0])
np.trim_zeros(a)

array([1, 2, 3, 4])

In [130]:
# unique - Deja los elementos unicos del array
a = np.array([1,1,1,1,2,2,2,2,3,3,3,3])
np.unique(a)

array([1, 2, 3])

## Leccion 3 - Operaciones con cadenas

In [1]:
import numpy as np

The numpy.char module provides a set of vectorized string operations for arrays of type numpy.string_ or numpy.unicode_. 

In [5]:
# add - Devuelve la concatenación de cadenas de elementos para dos matrices de str o unicode.
a = np.array(['A', 'B', 'C'], dtype = np.str)
b = np.array(['D', 'E', 'F'], dtype = np.str)

np.char.add(a,b)

array(['AD', 'BE', 'CF'], dtype='<U2')

In [8]:
# multiply - Devuelve (a * i), es decir, concatenación múltiple de cadenas, por elementos.
np.char.multiply(a, [2,3,4])

array(['AA', 'BBB', 'CCCC'], dtype='<U4')

In [13]:
# capitalize - Devuelve una copia de a con solo el primer carácter de cada elemento en mayúscula.
nombres = np.array(['maria', 'antonio', 'francisco'], dtype = np.str)
np.char.capitalize(nombres)

array(['Maria', 'Antonio', 'Francisco'], dtype='<U9')

In [18]:
# replace - Devuelve un array después de reemplazar los caracteres
np.char.replace(nombres, 'mar', 'sof')

array(['sofia', 'antonio', 'francisco'], dtype='<U9')

In [19]:
# split - Para cada elemento de a, devuelve una lista de las palabras de la cadena, utilizando sep como cadena delimitadora.
nombre = np.array(['Mi nombre es Abraham Requena'])
np.char.split(nombre, sep=' ')

array([list(['Mi', 'nombre', 'es', 'Abraham', 'Requena'])], dtype=object)

In [20]:
c = np.array(['  Hola  ', '  Adios '])
np.char.strip(c)

array(['Hola', 'Adios'], dtype='<U8')

### Comparación

In [21]:
# equal - Valores iguales
a = np.array(['A', 'B', 'C'], dtype = np.str)
b = np.array(['D', 'B', 'F'], dtype = np.str)

np.char.equal(a,b)

array([False,  True, False])

In [22]:
np.char.not_equal(a,b)

array([ True, False,  True])

In [26]:
# greater_equal . Compara el mayor o igual a nivel cadena. A < B, o F > C
np.char.greater_equal(a,b)

array([False,  True, False])

In [28]:
# less_equal
np.char.less_equal(a,b)

array([ True,  True,  True])

### Información sobre la cadena

In [30]:
# endswith - Devuelve True si la palabra acaba en el char que definimos
c = np.array(['Hola', 'Adios'])
np.char.endswith(c, suffix='ios')

array([False,  True])

In [31]:
# startswith - Devuelve True si la palabra comienza en el char que definimos
np.char.startswith(c, prefix='Ad')

array([False,  True])

In [36]:
# islower - Devuelve True si todos los caracteres están en minusculas
c = np.array(['HOLA', 'adios'])
np.char.islower(c)

array([False,  True])

In [37]:
# islower - Devuelve True si todos los caracteres están en mayusculas
c = np.array(['HOLA', 'adios'])
np.char.isupper(c)

array([ True, False])

In [39]:
# isdigit - Devuelve True si todos los elementos son numericos
c = np.array(['HOLA', 'adios', '123'])
np.char.isdigit(c)

array([False, False,  True])

## Leccion 4 - Algebra lineal

Numpy nos proporciona métodos para trabajar con álgebra lineal. 

In [1]:
import numpy as np

In [7]:
a = np.array([[3, 2], [1, 3]])
b = np.array([[2, 2], [1, 2]])

$A = \begin{pmatrix}
3 & 2 \\
1 & 3 \\
\end{pmatrix}$
$B = \begin{pmatrix}
2 & 2 \\
1 & 2 \\
\end{pmatrix}$
$AxB = \begin{pmatrix}
8 & 10 \\
5 & 8 \\
\end{pmatrix}$

In [10]:
# Producto matricial de dos matrices
np.dot(a, b)

array([[ 8, 10],
       [ 5,  8]])

In [11]:
# vdot - Devuelve el producto escalar de dos vectores.
np.vdot(a,b)

17

El calculo de arriba sería: 3\*2 + 2\*2 + 1\*1 + 3\*2 = 17

In [26]:
# inner - Producto interno de dos matrices.
a = np.arange(6).reshape((2,3))
b = np.arange(3)

In [27]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
b

array([0, 1, 2])

In [29]:
np.inner(a, b)

array([ 5, 14])

El calculo sería: 
- 0 x 0 + 1 x 1 + 2 x 2 = 5
- 3 x 0 + 4 x 1 + 5 x 1 = 14

In [31]:
# matrix_power - Eleve una matriz cuadrada a la potencia (entera) n.
m = np.array([[2,3], [1,4]])
np.linalg.matrix_power(m, 2)

array([[ 7, 18],
       [ 6, 19]])

La matriz m^2 es igual a el producto escalar de m x m. Podemos comprobar el resultado con *np.dot*

In [33]:
np.dot(m,m)

array([[ 7, 18],
       [ 6, 19]])

Si no conocéis que son los valores y vectores propios de una matriz, podéis investigar facilmente en la red. Lo que sí debéis saber es que numpy nos proporciona un método para calcularlo de manera rápida y sencilla.

In [38]:
# eig - Calcula los valores propios y los vectores propios rectos de una matriz cuadrada
m = np.diag([4,3,2,1])
m

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

In [39]:
np.linalg.eig(m)

(array([4., 3., 2., 1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [40]:
# det - Calcula el determinante de una matriz.

In [42]:
np.linalg.det(m)

24.000000000000004

In [43]:
# solve - Resuelve una ecuación con matrices
a

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
b

array([0, 1, 2])

In [66]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

El calculo de arriba sería:
- 3 \* x0 + 1 \* x1 = 9
- 1 \* x0 + 2 \* x1 = 8

## Lección 6 - Funciones lógicas

In [67]:
import numpy as np

Numpy nos proporciona una serie de funciones lógicas para realizar comprobaciones. Todas las funciones que veamos en esta lección devuelven como resultado True o False

In [68]:
# all - Comprueba si todos los elementos de una matriz o array cumplen una condicion

a = np.array([2,3,4,5])
np.all(a < 10)

True

In [70]:
# any - Comprueba si algún elemento de una matriz o array cumplen una condicion

a = np.array([2,3,4,5])
np.any(a < 0)

False

In [71]:
# logical_and : Función lógica and. Devuelve True si todas las comprobaciones son ciertas
np.logical_and(a > 2, a < 4)

array([False,  True, False, False])

In [72]:
# logical_or : Función lógica or. Devuelve True si alguna de las comprobaciones son ciertas
np.logical_or(a > 2, a < 4)

array([ True,  True,  True,  True])

In [83]:
# Devuelve True si todas las diferencia en valor absoluto es menor a la tolerancia.
np.allclose([1e10,1e-7], [1.00001e10,1.000001e-7], rtol=0.00001)

True

In [85]:
#isclose - Igual, pero valor a valor
np.isclose([1e10,1e-7], [1.001e10,1.000001e-7], rtol=0.00001)

array([False,  True])

In [91]:
#equal - Verdadero si dos arrays o matrices son iguales en cuanto a dimensiones y valores
np.array_equal(np.array([1,2,3]), np.array([1,2,3]))

True

In [92]:
np.array_equal(np.array([1,2,3]), np.array([1,2,3,4]))

False

In [94]:
# greater - Devuelve True si el valor es mayor.
np.greater(np.array([1,2,3]), np.array([3,2,1]))

array([False, False,  True])

In [95]:
np.greater_equal(np.array([1,2,3]), np.array([3,2,1]))

array([False,  True,  True])

In [96]:
# less y less_equal funcionan igual.
np.less(np.array([1,2,3]), np.array([3,2,1]))

array([ True, False, False])

In [97]:
np.less_equal(np.array([1,2,3]), np.array([3,2,1]))

array([ True,  True, False])

## Leccion 7 - Funciones matemáticas

In [98]:
import numpy as np

Dentro de todas las funciones matemáticas que tenemos disponibles en Numpy, destacamos las siguientes categorías.

### Redondeo

In [107]:
a = 2.49264

In [108]:
# round - Redonde un número a las cifras que definamos
np.round(a, 1)

2.5

In [112]:
array = np.array([1.435, 13.1435, 4.916])
np.round(array, 2)

array([ 1.44, 13.14,  4.92])

In [115]:
# floor - Devuelve el suelo - el número entero pequeño más cercano
np.floor(array)

array([ 1., 13.,  4.])

In [116]:
# Devuelve el techo - el siguiente número entero
np.ceil(array)

array([ 2., 14.,  5.])

### Sumas y productos

In [117]:
# prod - Devuelve el producto de los elementos de la matriz sobre un eje dado
b = np.array([2,3,4])
np.prod(b)

24

In [126]:
b = np.array([[2,3,4],[2,2,2]])
np.prod(b, axis = 0)

array([4, 6, 8])

In [127]:
np.prod(b, axis = 1)

array([24,  8])

In [128]:
# sum - Mismo funcionamiento que prod, pero en este caso realizando la suma

In [129]:
np.sum(b)

15

In [132]:
np.sum(b, axis = 0)

array([4, 5, 6])

In [131]:
np.sum(b, axis = 1)

array([9, 6])

### Exponentes y logaritmos

In [134]:
#exp - Calcula el exponencial de todos los elementos en la matriz de entrada.
b

array([[2, 3, 4],
       [2, 2, 2]])

In [135]:
np.exp(b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

El exponencial se calcula como el número e elevado al escalar. Es decir, es equivalente a:

In [141]:
np.power(np.e, b)

array([[ 7.3890561 , 20.08553692, 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ]])

Para el cálculo de logaritmos tenemos las opciones:
- log: base e
- log10: base 10
- log2: base 2

In [142]:
p = np.power(np.e, b)
np.log(p)

array([[2., 3., 4.],
       [2., 2., 2.]])

In [143]:
np.log10(b)

array([[0.30103   , 0.47712125, 0.60205999],
       [0.30103   , 0.30103   , 0.30103   ]])

In [144]:
np.power(10, np.log10(b))

array([[2., 3., 4.],
       [2., 2., 2.]])

In [145]:
np.log2(b)

array([[1.       , 1.5849625, 2.       ],
       [1.       , 1.       , 1.       ]])

In [146]:
np.power(2, np.log2(b))

array([[2., 3., 4.],
       [2., 2., 2.]])

### Operaciones aritméticas

Hacen referencia a operaciones básicas de suma, resta, multiplicación o división de cada elemento del array.

In [155]:
a = np.array([[1,2,3,4], [4,3,2,1]])
b = np.array([4,3,2,1])

In [156]:
# Suma
np.add(a,b)

array([[5, 5, 5, 5],
       [8, 6, 4, 2]])

In [157]:
# Resta
np.subtract(a,b)

array([[-3, -1,  1,  3],
       [ 0,  0,  0,  0]])

In [158]:
# Multiplicacion
np.multiply(a,b)

array([[ 4,  6,  6,  4],
       [16,  9,  4,  1]])

In [162]:
# Division
np.divide(a,b)

array([[0.25      , 0.66666667, 1.5       , 4.        ],
       [1.        , 1.        , 1.        , 1.        ]])

## Lección 8 - Funciones estadísticas

In [163]:
import numpy as np

Las funciones estadísticas también son realmente interesantes. Son bastante usadas cualquier analísis de datos

### Funciones relacionadas con el orden

In [168]:
# min y max devuelven los valores minimos y maximos de un array
a = np.array([2,5,6,10])
print("Min", np.min(a))
print("Max", np.max(a))

Min 2
Max 10


In [169]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [174]:
np.min(b, axis = 1) # Axis 1 por filas

array([0, 4, 8])

In [175]:
np.min(b, axis = 0) # Axis 0 por columnas

array([0, 1, 2, 3])

In [212]:
# percentile - Calcule el percentil q-ésimo de los datos a lo largo del eje especificado.
b = np.arange(0, 101)
b


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [213]:
np.percentile(b, q = 11)

11.0

In [214]:
# Idem para el quantil. 

In [215]:
np.quantile(b, q = 0.25)

25.0

### Medias y varianzas

In [216]:
# median - Calcula la mediana (valor central)
np.median(b)

50.0

In [217]:
np.median(np.array([1,2,0,100,200,300,50]))

50.0

In [221]:
# average o media (con pesos)
a = np.array([1,2,3,4])
np.average(a)

2.5

In [225]:
np.average(a, weights=[2,2,1,1])

2.1666666666666665

La cuenta sería:
avg = sum(a * pesos) / sum(pesos)

1 x 2 + 2 x 2 + 3 x 1 + 4 x 1 = 13 &rarr; 13 / 6 = 2.16

In [226]:
# mean - Practicamente idéntico
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [227]:
np.mean(b, axis = 0) # Media por columnas

array([4.5, 5.5, 6.5])

In [228]:
np.mean(b, axis = 1) # Media por filas

array([ 1.,  4.,  7., 10.])

In [229]:
# std - Desviacion estándar
np.std(b, axis = 0)

array([3.35410197, 3.35410197, 3.35410197])

In [230]:
np.std(b)

3.452052529534663

La desviación estándar es la raíz cuadrada del promedio de las desviaciones al cuadrado de la media, es decir: 

std = sqrt(mean(abs(x - x.mean())\**2))

In [231]:
# var - Varianza
np.var(b, axis = 1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])

La varianza es el promedio de las desviaciones cuadradas de la media, es decir: 

var = mean (abs (x - x.mean ()) \** 2).

**La desviación estándar es la raiz cuadrada de la varianza.**

In [237]:
std = np.std(b, axis = 0)
print(std)
var = np.var(b, axis = 0)
print(var)

[3.35410197 3.35410197 3.35410197]
[11.25 11.25 11.25]


In [238]:
np.sqrt(var)

array([3.35410197, 3.35410197, 3.35410197])